# Default Blockchain Node Configuration
# This is the default configuration file for the blockchain node

[node]
name = "blockchain-node"
data_dir = "./data"
genesis_block_reward = 50.0

[database]
url = "sqlite:./data/blockchain.db"
max_connections = 10
connection_timeout_secs = 30
enable_migrations = true

[mining]
difficulty = 4
block_reward = 12.5
max_block_time_secs = 300  # 5 minutes
difficulty_adjustment_interval = 2016  # blocks
target_block_time_secs = 600  # 10 minutes
enabled = false

[network]
listen_port = 9000
bootstrap_peers = []
max_peers = 50
sync_interval_secs = 30
connection_timeout_secs = 10
enabled = false

[api]
enabled = true
bind_address = "127.0.0.1"
port = 8080
cors_enabled = true
cors_origins = ["*"]
rate_limit_requests_per_minute = 100
request_timeout_secs = 30

[contracts]
enabled = true
max_memory_mb = 16
execution_timeout_secs = 30
max_gas_limit = 1000000
gas_price = 0.001

[logging]
level = "info"
format = "json"

[logging.output]
console = true