# Development Configuration
# Configuration optimized for development and testing

[node]
name = "dev-blockchain-node"
data_dir = "./dev-data"
genesis_block_reward = 100.0

[database]
url = "sqlite:./dev-data/blockchain.db"
max_connections = 5
connection_timeout_secs = 10
enable_migrations = true

[mining]
difficulty = 2  # Lower difficulty for faster mining in development
block_reward = 25.0
max_block_time_secs = 60  # 1 minute
difficulty_adjustment_interval = 100  # blocks
target_block_time_secs = 30  # 30 seconds for faster development
enabled = true

[network]
listen_port = 9001
bootstrap_peers = []
max_peers = 10
sync_interval_secs = 10
connection_timeout_secs = 5
enabled = true

[api]
enabled = true
bind_address = "127.0.0.1"
port = 8081
cors_enabled = true
cors_origins = ["http://localhost:3000", "http://localhost:8080"]
rate_limit_requests_per_minute = 1000  # Higher limit for development
request_timeout_secs = 60

[contracts]
enabled = true
max_memory_mb = 32  # More memory for development
execution_timeout_secs = 60  # Longer timeout for debugging
max_gas_limit = 2000000
gas_price = 0.0001  # Lower gas price for testing

[logging]
level = "debug"
format = "pretty"

[logging.output]
console = true